<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net9.0-windows</TargetFramework>
        <RollForward>Major</RollForward>
        <PublishReadyToRun>false</PublishReadyToRun>
        <TieredCompilation>false</TieredCompilation>
        <UseWindowsForms>true</UseWindowsForms>
    </PropertyGroup>
    <PropertyGroup>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <ApplicationIcon>Icon.ico</ApplicationIcon>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="MonoGame.Framework.WindowsDX" Version="3.8.*"/>
        <PackageReference Include="MonoGame.Content.Builder.Task" Version="3.8.5" />
    </ItemGroup>
    <ItemGroup>
      <ProjectReference Include="..\HoraceInSpacePhysicsLib\HoraceInSpacePhysicsLib.csproj" />
    </ItemGroup>
    <ItemGroup>
      <None Update="Content\horace.png">
        <CopyToOutputDirectory>Never</CopyToOutputDirectory>
      </None>
      <None Update="Content\asteroid_big.png">
        <CopyToOutputDirectory>Never</CopyToOutputDirectory>
      </None>
      <None Update="Content\asteroid_medium.png">
        <CopyToOutputDirectory>Never</CopyToOutputDirectory>
      </None>
      <None Update="Content\asteroid_small.png">
        <CopyToOutputDirectory>Never</CopyToOutputDirectory>
      </None>
      <None Update="Content\ufo.png">
        <CopyToOutputDirectory>Never</CopyToOutputDirectory>
      </None>
      <None Update="Content\thruster.png">
        <CopyToOutputDirectory>Never</CopyToOutputDirectory>
      </None>
      <None Update="Content\bullet.png">
        <CopyToOutputDirectory>Never</CopyToOutputDirectory>
      </None>
      <None Update="Content\minecraft_font.ttf">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Content\File.spritefont">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Content\asteroid_giant.png">
        <CopyToOutputDirectory>Never</CopyToOutputDirectory>
      </None>
      <None Update="Content\shadow_overlay_big.png">
        <CopyToOutputDirectory>Never</CopyToOutputDirectory>
      </None>
      <None Update="Content\shadow_overlay_medium.png">
        <CopyToOutputDirectory>Never</CopyToOutputDirectory>
      </None>
      <None Update="Content\shadow_overlay_small.png">
        <CopyToOutputDirectory>Never</CopyToOutputDirectory>
      </None>
      <None Update="Content\shadow_overlay_giant.png">
        <CopyToOutputDirectory>Never</CopyToOutputDirectory>
      </None>
      <None Update="Content\shadow_overlay_enormous.png">
        <CopyToOutputDirectory>Never</CopyToOutputDirectory>
      </None>
      <None Update="Content\asteroid_enormous.png">
        <CopyToOutputDirectory>Never</CopyToOutputDirectory>
      </None>
    </ItemGroup>
</Project>